name: Java Test and Allure Report

on:
  workflow_dispatch: # Tương đương với rules: if: $CI_PIPELINE_SOURCE == "web"

jobs:
  run_test:
    runs-on: ubuntu-latest
    container:
      image: daw5sonvu/mvnedge:j26m3e138 # Sử dụng đúng image của bạn
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Maven Tests
        run: mvn clean verify

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          retention-days: 7

  generate_report:
    runs-on: ubuntu-latest
    needs: run_test
    if: always()
    container:
      image: daw5sonvu/allure:3.34
    
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Generate Allure Report
        run: |
          allure generate --single-file --clean ./target/allure-results -o public

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: public/
          retention-days: 30